# RANDOM FOREST 

## COMPANY DATA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# loading data 
data = pd.read_csv("Company_Data.csv")
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [3]:
data.loc[data.Sales >=8.5,'sales']= 'high'
data.loc[data.Sales <8.5,'sales']= 'low'

In [4]:
data.drop('Sales',1,inplace=True)

C:\Users\rakes\AppData\Local\Temp/ipykernel_8920/3546655252.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data.drop('Sales',1,inplace=True)


In [5]:
data.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [6]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['US']= label_encoder.fit_transform(data['US']) 
data['US'].unique() 

array([1, 0])

In [7]:
label_encoder = preprocessing.LabelEncoder() 
data['Urban']= label_encoder.fit_transform(data['Urban']) 

In [8]:
label_encoder = preprocessing.LabelEncoder() 
data['ShelveLoc']= label_encoder.fit_transform(data['ShelveLoc'])

In [9]:
colnames = list(data.columns)
predictors = colnames[0:10]
target = colnames[10]

In [10]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [11]:
target


'sales'

In [12]:
label_encoder = preprocessing.LabelEncoder() 
data['sales']= label_encoder.fit_transform(data['sales']) 

In [13]:
X = data[predictors]
Y = data[target]

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")

In [15]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [16]:
rf.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=588000992),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1352387139),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1264017398),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=600027806),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1001801283),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=812573727),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=923750329),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=948005073),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
           

In [18]:
rf.classes_

array([0, 1])

In [19]:
rf.n_classes_

2

In [20]:
rf.n_classes_

2

In [21]:
rf.n_outputs_

1

In [22]:
data['rf_pred'] = rf.predict(X)

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred'])

array([[143,   0],
       [  0, 257]], dtype=int64)

### Now will try with 500 decision tress

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=500,criterion="entropy")

In [25]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=500, n_jobs=2,
                       oob_score=True)

In [26]:
data['rf_pred2'] = rf.predict(X)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred2'])

array([[143,   0],
       [  0, 257]], dtype=int64)

## FRAUD CHECK

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
# loading data 
data = pd.read_csv("Fraud_check.csv")
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [30]:
data.loc[data['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
data.loc[data['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [31]:
data.head(2)

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good

In [32]:
data.drop('Taxable.Income',1,inplace=True)

C:\Users\rakes\AppData\Local\Temp/ipykernel_8920/2031450657.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data.drop('Taxable.Income',1,inplace=True)


In [33]:
data['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [34]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['Marital.Status']= label_encoder.fit_transform(data['Marital.Status']) 
data['Marital.Status'].unique() 

array([2, 0, 1])

In [35]:
data.head(2)

Undergrad  Marital.Status  City.Population  Work.Experience Urban  \
0        NO               2            50047               10   YES   
1       YES               0           134075               18   YES   

  Taxable_Income  
0           Good  
1           Good

In [36]:
data.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [37]:
data['Undergrad']= label_encoder.fit_transform(data['Undergrad']) 
data['Undergrad'].unique() 

array([0, 1])

In [38]:
data.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [39]:
data['Urban']= label_encoder.fit_transform(data['Urban']) 
data['Urban'].unique() 

array([1, 0])

In [40]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [41]:
colnames = list(data.columns)
predictors = colnames[0:5]
target = colnames[5]

In [42]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [43]:
target

'Taxable_Income'

In [44]:
X = data[predictors]
Y = data[target]

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [47]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [48]:
data['rf_pred'] = rf.predict(X)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['Taxable_Income'],data['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)